"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { buildCaptionCues } from "@kade/editor-core/captions";
import { getOutputDuration, sourceTimeToTimelineTime, timelineTimeToSourceTime } from "@kade/editor-core/ranges";
import { timelineStateSchema, type EditPlan, type TimelineState } from "@kade/editor-core/schema";
import { useEditorStore } from "@/lib/editor-store";
import type { EditorData } from "@/lib/editor-types";

const ms = (value: number) => `${Math.floor(value / 60_000)}:${String(Math.floor((value % 60_000) / 1000)).padStart(2, "0")}.${String(Math.floor((value % 1000) / 100)).padStart(1, "0")}`;
const statusTr: Record<string, string> = { queued: "Kuyrukta", processing: "İşleniyor", completed: "Tamamlandı", failed: "Başarısız", ready: "Hazır" };

export function EditorClient({ initialData }: { initialData: EditorData }) {
  const [data, setData] = useState(initialData); const [state, setState] = useState<TimelineState | null>(() => initialData.timeline ? timelineStateSchema.parse(initialData.timeline.stateJson) : null); const [command, setCommand] = useState("0.7 saniyeden uzun sessizlikleri kes, ııı ve şey kelimelerini çıkar, 9:16 yap ve Kade altyazılarını aç."); const [agentStatus, setAgentStatus] = useState("Hazır"); const [report, setReport] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [currentMs, setCurrentMs] = useState(0); const videoRef = useRef<HTMLVideoElement>(null); const frameRef = useRef<number | null>(null);
  const { leftTab, rightTab, zoom, selectedWordIndexes, setLeftTab, setRightTab, setZoom, selectWord, clearSelection } = useEditorStore();

  const refresh = useCallback(async () => { const response = await fetch(`/api/projects/${data.project.id}`, { cache: "no-store" }); if (!response.ok) return; const next = await response.json() as EditorData; setData(next); if (next.timeline) setState(timelineStateSchema.parse(next.timeline.stateJson)); }, [data.project.id]);
  useEffect(() => { if (data.project.status === "ready" && !data.exports.some((item) => item.status === "queued" || item.status === "processing")) return; const timer = setInterval(refresh, 1600); return () => clearInterval(timer); }, [data.project.status, data.exports, refresh]);
  const duration = state ? getOutputDuration(state) : 0;
  const included = useCallback((sourceMs: number) => state ? sourceTimeToTimelineTime(state.includedRanges, sourceMs) !== null : true, [state]);
  const captions = useMemo(() => state ? buildCaptionCues(data.words.map((word) => ({ ...word, confidence: word.confidence ? Number(word.confidence) : null })), state.includedRanges) : [], [data.words, state]);
  const activeCaption = captions.find((cue) => currentMs >= cue.startMs && currentMs <= cue.endMs);
  const activeOverlay = state?.overlays.find((overlay) => currentMs >= overlay.timelineStartMs && currentMs <= overlay.timelineStartMs + overlay.durationMs);

  useEffect(() => { const loop = () => { const video = videoRef.current; if (video && state) { const sourceMs = video.currentTime * 1000; let output = sourceTimeToTimelineTime(state.includedRanges, sourceMs); if (output === null && !video.paused) { const next = state.includedRanges.find((range) => range.sourceStartMs > sourceMs); if (next) { video.currentTime = next.sourceStartMs / 1000; output = sourceTimeToTimelineTime(state.includedRanges, next.sourceStartMs); } else { video.pause(); output = duration; } } if (output !== null) setCurrentMs(output); } frameRef.current = requestAnimationFrame(loop); }; frameRef.current = requestAnimationFrame(loop); return () => { if (frameRef.current) cancelAnimationFrame(frameRef.current); }; }, [duration, state]);
  const seekOutput = (outputMs: number) => { if (!state || !videoRef.current) return; const source = timelineTimeToSourceTime(state.includedRanges, outputMs); if (source !== null) { videoRef.current.currentTime = source / 1000; setCurrentMs(outputMs); } };

  async function execute(text: string, plan?: EditPlan) { setBusy(true); setAgentStatus("Planlanıyor"); setReport([]); try { setAgentStatus("Doğrulanıyor"); const response = await fetch(`/api/projects/${data.project.id}/commands`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ text, plan }) }); setAgentStatus("Uygulanıyor"); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setState(timelineStateSchema.parse(payload.state)); setReport([...payload.report, `Tahmini süre ${ms(payload.beforeDurationMs)} → ${ms(payload.afterDurationMs)}`]); setAgentStatus("Tamamlandı"); clearSelection(); await refresh(); } catch (error) { setAgentStatus("Başarısız"); setReport([error instanceof Error ? error.message : "Komut uygulanamadı."]); } finally { setBusy(false); } }
  async function history(direction: "undo" | "redo") { setBusy(true); try { const response = await fetch(`/api/projects/${data.project.id}/history`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ direction }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setState(timelineStateSchema.parse(payload.state)); await refresh(); } catch (error) { setReport([error instanceof Error ? error.message : "Geçmiş işlemi başarısız."]); } finally { setBusy(false); } }
  async function removeSelection() { if (!selectedWordIndexes.length) return; const selected = data.words.filter((word) => selectedWordIndexes.includes(word.wordIndex)); const startMs = selected[0]?.startMs; const endMs = selected.at(-1)?.endMs; if (startMs === undefined || endMs === undefined) return; await execute("Transkript seçimini sil", { operations: [{ type: "delete_source_ranges", ranges: [{ startMs, endMs }] }] }); }
  async function saveVersion() { const name = window.prompt("Bu versiyona bir ad verin", `Kurgu v${(data.timeline?.currentVersion ?? 0) + 1}`); if (!name) return; await fetch(`/api/projects/${data.project.id}/versions`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name }) }); await refresh(); }
  async function startExport() { setBusy(true); const response = await fetch(`/api/projects/${data.project.id}/exports`, { method: "POST" }); const payload = await response.json(); if (!response.ok) setReport([payload.error]); else { setRightTab("exports"); setReport(["Export kuyruğa eklendi."]); await refresh(); } setBusy(false); }
  async function togglePlay() { const video = videoRef.current; if (!video) return; if (video.paused) await video.play(); else video.pause(); }

  useEffect(() => { const key = (event: KeyboardEvent) => { if (event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement) return; if (event.code === "Space") { event.preventDefault(); void togglePlay(); } if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "z") { event.preventDefault(); void history(event.shiftKey ? "redo" : "undo"); } if (event.key === "Delete") void removeSelection(); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); });

  if (!state || !data.asset || data.asset.status !== "ready") return <main id="main" className="processing-page"><div className="processing-mark"><span>{data.jobs[0]?.progress ?? 0}</span><i>%</i></div><p className="eyebrow">INGEST / {statusTr[data.asset?.status ?? data.jobs[0]?.status ?? "queued"]}</p><h1>{data.project.name}</h1><div className="processing-line"><span style={{ width: `${data.jobs[0]?.progress ?? 0}%` }} /></div><p>Proxy, waveform, sessizlik analizi ve kelime zaman kodları hazırlanıyor.</p>{(data.asset?.errorMessage || data.jobs[0]?.errorMessage) && <p className="form-error">{data.asset?.errorMessage ?? data.jobs[0]?.errorMessage}</p>}<Link href="/">← Dashboard</Link></main>;

  return <main id="main" className="editor-shell">
    <div className="editor-toolbar"><Link href="/" aria-label="Dashboard">←</Link><div><strong>{data.project.name}</strong><span><i /> {statusTr[data.asset.status] ?? data.asset.status}</span></div><div className="toolbar-actions"><button onClick={() => history("undo")} disabled={busy || (data.timeline?.currentVersion ?? 0) <= 0} aria-label="Geri al">↶ <small>UNDO</small></button><button onClick={() => history("redo")} disabled={busy} aria-label="Yinele">↷ <small>REDO</small></button><button onClick={saveVersion}>◇ <small>VERSİYON</small></button><select aria-label="Çıktı oranı" value={state.canvas.aspectRatio} onChange={(event) => execute(`${event.target.value} yap`, { operations: [{ type: "set_aspect_ratio", value: event.target.value as "16:9" | "9:16" | "1:1", fitMode: event.target.value === "16:9" ? "contain" : "cover" }] })}><option>16:9</option><option>9:16</option><option>1:1</option></select><button className="export-button" onClick={startExport} disabled={busy}>EXPORT ↗</button></div></div>
    <section className="left-panel panel"><div className="tabs"><button className={leftTab === "agent" ? "active" : ""} onClick={() => setLeftTab("agent")}>AI KURGU</button><button className={leftTab === "transcript" ? "active" : ""} onClick={() => setLeftTab("transcript")}>TRANSKRİPT</button></div>{leftTab === "agent" ? <div className="agent-panel"><div className="agent-intro"><span className="agent-glyph">K</span><div><strong>Kurgu Ajanı</strong><small>{agentStatus}</small></div></div><p>Türkçe veya İngilizce yaz. Uygulanan işlemleri ve gerçek süre farkını raporlarım.</p><form onSubmit={(event) => { event.preventDefault(); void execute(command); }}><textarea aria-label="Kurgu komutu" value={command} onChange={(event) => setCommand(event.target.value)} rows={7} /><button disabled={busy}>{busy ? agentStatus.toUpperCase() : "KOMUTU UYGULA →"}</button></form>{report.length > 0 && <div className={`agent-report ${agentStatus === "Başarısız" ? "error" : ""}`}><strong>{agentStatus}</strong>{report.map((item) => <p key={item}>• {item}</p>)}</div>}<div className="quick-commands"><small>HIZLI KOMUTLAR</small>{["Sessizlikleri kaldır", "Dolgu kelimelerini temizle", "Altyazıları aç", "Başına KADE MEDIA yazısı ekle"].map((text) => <button key={text} onClick={() => setCommand(text)}>{text}</button>)}</div></div> : <div className="transcript-panel"><div className="transcript-meta"><span>{data.words.length} KELİME</span>{selectedWordIndexes.length > 0 && <button onClick={removeSelection}>SEÇİMİ SİL ({selectedWordIndexes.length})</button>}</div><div className="words">{data.words.map((word) => { const cut = !included(word.startMs); const selected = selectedWordIndexes.includes(word.wordIndex); return <button key={word.id} className={`${cut ? "cut" : ""} ${selected ? "selected" : ""}`} onClick={(event) => { selectWord(word.wordIndex, event.shiftKey); if (!event.shiftKey && videoRef.current) videoRef.current.currentTime = word.startMs / 1000; }} title={`${ms(word.startMs)}${cut ? " · kesildi" : ""}`}>{word.text}</button>; })}</div><p className="selection-help">Tıkla: seek · Shift+tıkla: aralık seç · Delete: sil</p></div>}</section>
    <section className="player-stage"><div className="player-frame" style={{ aspectRatio: state.canvas.aspectRatio.replace(":", "/") }}><video ref={videoRef} src={data.proxyUrl ?? undefined} playsInline onClick={togglePlay}/>{state.captions.enabled && activeCaption && <div className={`caption caption-${state.captions.preset}`}>{activeCaption.text}</div>}{activeOverlay && <div className={`title-overlay title-${activeOverlay.position}`}>{activeOverlay.text}</div>}<div className="frame-corners" /></div><div className="transport"><button onClick={() => seekOutput(Math.max(0, currentMs - 5000))} aria-label="5 saniye geri">−5</button><button className="play" onClick={togglePlay} aria-label="Oynat veya duraklat">▶</button><button onClick={() => seekOutput(Math.min(duration, currentMs + 5000))} aria-label="5 saniye ileri">+5</button><time>{ms(currentMs)} <span>/ {ms(duration)}</span></time></div></section>
    <aside className="right-panel panel"><div className="tabs"><button className={rightTab === "media" ? "active" : ""} onClick={() => setRightTab("media")}>MEDYA</button><button className={rightTab === "settings" ? "active" : ""} onClick={() => setRightTab("settings")}>AYARLAR</button><button className={rightTab === "exports" ? "active" : ""} onClick={() => setRightTab("exports")}>EXPORT</button></div>{rightTab === "media" && <div className="inspector"><p className="inspector-label">PRIMARY / 001</p><div className="media-card"><div className="media-thumb">▶</div><div><strong>{data.asset.originalFilename}</strong><small>{data.asset.width}×{data.asset.height} · {ms(data.asset.durationMs ?? 0)}</small></div></div><dl><div><dt>DURUM</dt><dd>HAZIR</dd></div><div><dt>PROXY</dt><dd>H.264 / 720P</dd></div><div><dt>AI</dt><dd>{data.transcript?.provider.toUpperCase()}</dd></div><div><dt>DİL</dt><dd>{data.transcript?.language.toUpperCase()}</dd></div></dl></div>}{rightTab === "settings" && <div className="inspector settings"><label>ALTYAZI <select value={state.captions.enabled ? state.captions.preset : "off"} onChange={(event) => execute("Altyazı ayarı", { operations: [{ type: "set_captions", enabled: event.target.value !== "off", preset: event.target.value === "off" ? "kade-clean" : event.target.value as "kade-clean" | "kade-bold" | "minimal" }] })}><option value="off">Kapalı</option><option value="kade-clean">Kade Clean</option><option value="kade-bold">Kade Bold</option><option value="minimal">Minimal</option></select></label><label>FIT MODE <select value={state.canvas.fitMode} onChange={(event) => execute("Fit mode", { operations: [{ type: "set_aspect_ratio", value: state.canvas.aspectRatio, fitMode: event.target.value as "cover" | "contain" }] })}><option value="contain">Contain</option><option value="cover">Cover</option></select></label></div>}{rightTab === "exports" && <div className="inspector exports-list">{data.exports.length ? data.exports.map((item) => <article key={item.id}><div><strong>MP4 · {item.width}×{item.height}</strong><small>v{item.id.slice(0, 4)} · {statusTr[item.status] ?? item.status}</small></div><span>{item.progress}%</span>{item.status === "completed" && <a href={`/api/exports/${item.id}/download`}>İNDİR ↓</a>}{item.errorMessage && <p>{item.errorMessage}</p>}</article>) : <p className="muted">Henüz export yok.</p>}</div>}</aside>
    <section className="timeline"><div className="timeline-head"><div><strong>TIMELINE</strong><span>{ms(duration)} / SOURCE {ms(data.asset.durationMs ?? 0)}</span></div><label>ZOOM <input aria-label="Timeline zoom" type="range" min="1" max="3" step="0.25" value={zoom} onChange={(event) => setZoom(Number(event.target.value))}/></label></div><div className="timeline-scroll"><div className="timeline-canvas" style={{ width: `${zoom * 100}%` }} onClick={(event) => { const rect = event.currentTarget.getBoundingClientRect(); seekOutput(((event.clientX - rect.left) / rect.width) * duration); }}><div className="ruler">{Array.from({ length: 9 }, (_, index) => <span key={index} style={{ left: `${index * 12.5}%` }}>{ms(duration * index / 8)}</span>)}</div><div className="track"><label>V1</label><div className="track-body source-track">{state.includedRanges.map((range) => <span key={range.id} style={{ left: `${(range.sourceStartMs / (data.asset!.durationMs ?? 1)) * 100}%`, width: `${((range.sourceEndMs - range.sourceStartMs) / (data.asset!.durationMs ?? 1)) * 100}%` }}><i>VIDEO</i></span>)}</div></div><div className="track"><label>CC</label><div className="track-body caption-track">{state.captions.enabled && captions.map((cue) => <span key={cue.id} style={{ left: `${(cue.startMs / duration) * 100}%`, width: `${((cue.endMs - cue.startMs) / duration) * 100}%` }} />)}</div></div><div className="track"><label>TXT</label><div className="track-body overlay-track">{state.overlays.map((overlay) => <span key={overlay.id} style={{ left: `${(overlay.timelineStartMs / duration) * 100}%`, width: `${(overlay.durationMs / duration) * 100}%` }}>{overlay.text}</span>)}</div></div><div className="playhead" style={{ left: `${duration ? currentMs / duration * 100 : 0}%` }}><i /></div></div></div></section>
  </main>;
}
